// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'api/workflow.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1509219725;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ss_subtitle_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<SubtitleArtifact> crateApiWorkflowAcquireSubtitle({
    required String candidateId,
  });

  String crateApiSimpleComputeCid({
    required BigInt fileSize,
    required List<SampleChunk> chunks,
  });

  String crateApiSimpleDeriveSearchName({required String filename});

  Future<void> crateApiSimpleInitApp();

  VideoSamplePlan crateApiSimplePlanVideoSample({required BigInt fileSize});

  Future<WorkflowSubtitlePreviewPage> crateApiWorkflowPreviewSubtitle({
    required String candidateId,
    required int page,
  });

  Future<List<WorkflowSubtitleCandidate>> crateApiWorkflowSearchSubtitles({
    required String suggestedSearchName,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<SubtitleArtifact> crateApiWorkflowAcquireSubtitle({
    required String candidateId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(candidateId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_subtitle_artifact,
          decodeErrorData: sse_decode_subtitle_failure,
        ),
        constMeta: kCrateApiWorkflowAcquireSubtitleConstMeta,
        argValues: [candidateId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkflowAcquireSubtitleConstMeta =>
      const TaskConstMeta(
        debugName: "acquire_subtitle",
        argNames: ["candidateId"],
      );

  @override
  String crateApiSimpleComputeCid({
    required BigInt fileSize,
    required List<SampleChunk> chunks,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(fileSize, serializer);
          sse_encode_list_sample_chunk(chunks, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleComputeCidConstMeta,
        argValues: [fileSize, chunks],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleComputeCidConstMeta => const TaskConstMeta(
    debugName: "compute_cid",
    argNames: ["fileSize", "chunks"],
  );

  @override
  String crateApiSimpleDeriveSearchName({required String filename}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filename, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleDeriveSearchNameConstMeta,
        argValues: [filename],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeriveSearchNameConstMeta =>
      const TaskConstMeta(
        debugName: "derive_search_name",
        argNames: ["filename"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  VideoSamplePlan crateApiSimplePlanVideoSample({required BigInt fileSize}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(fileSize, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_sample_plan,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePlanVideoSampleConstMeta,
        argValues: [fileSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePlanVideoSampleConstMeta =>
      const TaskConstMeta(
        debugName: "plan_video_sample",
        argNames: ["fileSize"],
      );

  @override
  Future<WorkflowSubtitlePreviewPage> crateApiWorkflowPreviewSubtitle({
    required String candidateId,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(candidateId, serializer);
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workflow_subtitle_preview_page,
          decodeErrorData: sse_decode_subtitle_failure,
        ),
        constMeta: kCrateApiWorkflowPreviewSubtitleConstMeta,
        argValues: [candidateId, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkflowPreviewSubtitleConstMeta =>
      const TaskConstMeta(
        debugName: "preview_subtitle",
        argNames: ["candidateId", "page"],
      );

  @override
  Future<List<WorkflowSubtitleCandidate>> crateApiWorkflowSearchSubtitles({
    required String suggestedSearchName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(suggestedSearchName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_workflow_subtitle_candidate,
          decodeErrorData: sse_decode_subtitle_failure,
        ),
        constMeta: kCrateApiWorkflowSearchSubtitlesConstMeta,
        argValues: [suggestedSearchName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkflowSearchSubtitlesConstMeta =>
      const TaskConstMeta(
        debugName: "search_subtitles",
        argNames: ["suggestedSearchName"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ByteRange dco_decode_byte_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ByteRange(
      offset: dco_decode_u_64(arr[0]),
      length: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ByteRange> dco_decode_list_byte_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_byte_range).toList();
  }

  @protected
  List<MatchReason> dco_decode_list_match_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_match_reason).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SampleChunk> dco_decode_list_sample_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sample_chunk).toList();
  }

  @protected
  List<WorkflowSubtitleCandidate> dco_decode_list_workflow_subtitle_candidate(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_workflow_subtitle_candidate)
        .toList();
  }

  @protected
  MatchReason dco_decode_match_reason(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MatchReason(
      kind: dco_decode_match_reason_kind(arr[0]),
      value: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  MatchReasonKind dco_decode_match_reason_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MatchReasonKind.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SampleChunk dco_decode_sample_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SampleChunk(
      offset: dco_decode_u_64(arr[0]),
      bytes: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  SubtitleArtifact dco_decode_subtitle_artifact(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SubtitleArtifact(
      candidateId: dco_decode_String(arr[0]),
      bytes: dco_decode_list_prim_u_8_strict(arr[1]),
      format: dco_decode_subtitle_format(arr[2]),
    );
  }

  @protected
  SubtitleFailure dco_decode_subtitle_failure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SubtitleFailure(
      operation: dco_decode_subtitle_operation(arr[0]),
      kind: dco_decode_subtitle_failure_kind(arr[1]),
      detail: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  SubtitleFailureKind dco_decode_subtitle_failure_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SubtitleFailureKind.values[raw as int];
  }

  @protected
  SubtitleFormat dco_decode_subtitle_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SubtitleFormat.values[raw as int];
  }

  @protected
  SubtitleOperation dco_decode_subtitle_operation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SubtitleOperation.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoSamplePlan dco_decode_video_sample_plan(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return VideoSamplePlan(
      fileSize: dco_decode_u_64(arr[0]),
      ranges: dco_decode_list_byte_range(arr[1]),
    );
  }

  @protected
  WorkflowSubtitleCandidate dco_decode_workflow_subtitle_candidate(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return WorkflowSubtitleCandidate(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      languages: dco_decode_list_String(arr[2]),
      format: dco_decode_subtitle_format(arr[3]),
      matchScore: dco_decode_i_64(arr[4]),
      matchReasons: dco_decode_list_match_reason(arr[5]),
    );
  }

  @protected
  WorkflowSubtitlePreviewPage dco_decode_workflow_subtitle_preview_page(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WorkflowSubtitlePreviewPage(
      candidateId: dco_decode_String(arr[0]),
      lines: dco_decode_list_String(arr[1]),
      page: dco_decode_u_32(arr[2]),
      totalPages: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ByteRange sse_decode_byte_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_offset = sse_decode_u_64(deserializer);
    var var_length = sse_decode_u_64(deserializer);
    return ByteRange(offset: var_offset, length: var_length);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ByteRange> sse_decode_list_byte_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ByteRange>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_byte_range(deserializer));
    }
    return ans_;
  }

  @protected
  List<MatchReason> sse_decode_list_match_reason(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MatchReason>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_match_reason(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SampleChunk> sse_decode_list_sample_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SampleChunk>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sample_chunk(deserializer));
    }
    return ans_;
  }

  @protected
  List<WorkflowSubtitleCandidate> sse_decode_list_workflow_subtitle_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WorkflowSubtitleCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_workflow_subtitle_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  MatchReason sse_decode_match_reason(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_match_reason_kind(deserializer);
    var var_value = sse_decode_opt_String(deserializer);
    return MatchReason(kind: var_kind, value: var_value);
  }

  @protected
  MatchReasonKind sse_decode_match_reason_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MatchReasonKind.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SampleChunk sse_decode_sample_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_offset = sse_decode_u_64(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return SampleChunk(offset: var_offset, bytes: var_bytes);
  }

  @protected
  SubtitleArtifact sse_decode_subtitle_artifact(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_candidateId = sse_decode_String(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_format = sse_decode_subtitle_format(deserializer);
    return SubtitleArtifact(
      candidateId: var_candidateId,
      bytes: var_bytes,
      format: var_format,
    );
  }

  @protected
  SubtitleFailure sse_decode_subtitle_failure(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_operation = sse_decode_subtitle_operation(deserializer);
    var var_kind = sse_decode_subtitle_failure_kind(deserializer);
    var var_detail = sse_decode_opt_String(deserializer);
    return SubtitleFailure(
      operation: var_operation,
      kind: var_kind,
      detail: var_detail,
    );
  }

  @protected
  SubtitleFailureKind sse_decode_subtitle_failure_kind(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SubtitleFailureKind.values[inner];
  }

  @protected
  SubtitleFormat sse_decode_subtitle_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SubtitleFormat.values[inner];
  }

  @protected
  SubtitleOperation sse_decode_subtitle_operation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SubtitleOperation.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoSamplePlan sse_decode_video_sample_plan(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileSize = sse_decode_u_64(deserializer);
    var var_ranges = sse_decode_list_byte_range(deserializer);
    return VideoSamplePlan(fileSize: var_fileSize, ranges: var_ranges);
  }

  @protected
  WorkflowSubtitleCandidate sse_decode_workflow_subtitle_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_languages = sse_decode_list_String(deserializer);
    var var_format = sse_decode_subtitle_format(deserializer);
    var var_matchScore = sse_decode_i_64(deserializer);
    var var_matchReasons = sse_decode_list_match_reason(deserializer);
    return WorkflowSubtitleCandidate(
      id: var_id,
      name: var_name,
      languages: var_languages,
      format: var_format,
      matchScore: var_matchScore,
      matchReasons: var_matchReasons,
    );
  }

  @protected
  WorkflowSubtitlePreviewPage sse_decode_workflow_subtitle_preview_page(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_candidateId = sse_decode_String(deserializer);
    var var_lines = sse_decode_list_String(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_totalPages = sse_decode_u_32(deserializer);
    return WorkflowSubtitlePreviewPage(
      candidateId: var_candidateId,
      lines: var_lines,
      page: var_page,
      totalPages: var_totalPages,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_byte_range(ByteRange self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.offset, serializer);
    sse_encode_u_64(self.length, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_byte_range(
    List<ByteRange> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_byte_range(item, serializer);
    }
  }

  @protected
  void sse_encode_list_match_reason(
    List<MatchReason> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_match_reason(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sample_chunk(
    List<SampleChunk> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sample_chunk(item, serializer);
    }
  }

  @protected
  void sse_encode_list_workflow_subtitle_candidate(
    List<WorkflowSubtitleCandidate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_workflow_subtitle_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_match_reason(MatchReason self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_match_reason_kind(self.kind, serializer);
    sse_encode_opt_String(self.value, serializer);
  }

  @protected
  void sse_encode_match_reason_kind(
    MatchReasonKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_sample_chunk(SampleChunk self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.offset, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_subtitle_artifact(
    SubtitleArtifact self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.candidateId, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_subtitle_format(self.format, serializer);
  }

  @protected
  void sse_encode_subtitle_failure(
    SubtitleFailure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_subtitle_operation(self.operation, serializer);
    sse_encode_subtitle_failure_kind(self.kind, serializer);
    sse_encode_opt_String(self.detail, serializer);
  }

  @protected
  void sse_encode_subtitle_failure_kind(
    SubtitleFailureKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_subtitle_format(
    SubtitleFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_subtitle_operation(
    SubtitleOperation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_sample_plan(
    VideoSamplePlan self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.fileSize, serializer);
    sse_encode_list_byte_range(self.ranges, serializer);
  }

  @protected
  void sse_encode_workflow_subtitle_candidate(
    WorkflowSubtitleCandidate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_String(self.languages, serializer);
    sse_encode_subtitle_format(self.format, serializer);
    sse_encode_i_64(self.matchScore, serializer);
    sse_encode_list_match_reason(self.matchReasons, serializer);
  }

  @protected
  void sse_encode_workflow_subtitle_preview_page(
    WorkflowSubtitlePreviewPage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.candidateId, serializer);
    sse_encode_list_String(self.lines, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.totalPages, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
