// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'api/xunlei.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CandidateRankingContext dco_decode_box_autoadd_candidate_ranking_context(
    dynamic raw,
  );

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ByteRange dco_decode_byte_range(dynamic raw);

  @protected
  CandidateRankingContext dco_decode_candidate_ranking_context(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ByteRange> dco_decode_list_byte_range(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RankedSubtitleCandidate> dco_decode_list_ranked_subtitle_candidate(
    dynamic raw,
  );

  @protected
  List<SampleChunk> dco_decode_list_sample_chunk(dynamic raw);

  @protected
  List<SubtitleCandidate> dco_decode_list_subtitle_candidate(dynamic raw);

  @protected
  List<XunleiCandidate> dco_decode_list_xunlei_candidate(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  RankedSubtitleCandidate dco_decode_ranked_subtitle_candidate(dynamic raw);

  @protected
  SampleChunk dco_decode_sample_chunk(dynamic raw);

  @protected
  SubtitleCandidate dco_decode_subtitle_candidate(dynamic raw);

  @protected
  SubtitlePreviewPage dco_decode_subtitle_preview_page(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoSamplePlan dco_decode_video_sample_plan(dynamic raw);

  @protected
  XunleiCandidate dco_decode_xunlei_candidate(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CandidateRankingContext sse_decode_box_autoadd_candidate_ranking_context(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ByteRange sse_decode_byte_range(SseDeserializer deserializer);

  @protected
  CandidateRankingContext sse_decode_candidate_ranking_context(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ByteRange> sse_decode_list_byte_range(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RankedSubtitleCandidate> sse_decode_list_ranked_subtitle_candidate(
    SseDeserializer deserializer,
  );

  @protected
  List<SampleChunk> sse_decode_list_sample_chunk(SseDeserializer deserializer);

  @protected
  List<SubtitleCandidate> sse_decode_list_subtitle_candidate(
    SseDeserializer deserializer,
  );

  @protected
  List<XunleiCandidate> sse_decode_list_xunlei_candidate(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  RankedSubtitleCandidate sse_decode_ranked_subtitle_candidate(
    SseDeserializer deserializer,
  );

  @protected
  SampleChunk sse_decode_sample_chunk(SseDeserializer deserializer);

  @protected
  SubtitleCandidate sse_decode_subtitle_candidate(SseDeserializer deserializer);

  @protected
  SubtitlePreviewPage sse_decode_subtitle_preview_page(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoSamplePlan sse_decode_video_sample_plan(SseDeserializer deserializer);

  @protected
  XunleiCandidate sse_decode_xunlei_candidate(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_candidate_ranking_context(
    CandidateRankingContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_byte_range(ByteRange self, SseSerializer serializer);

  @protected
  void sse_encode_candidate_ranking_context(
    CandidateRankingContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_byte_range(
    List<ByteRange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ranked_subtitle_candidate(
    List<RankedSubtitleCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sample_chunk(
    List<SampleChunk> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_subtitle_candidate(
    List<SubtitleCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_xunlei_candidate(
    List<XunleiCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_ranked_subtitle_candidate(
    RankedSubtitleCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sample_chunk(SampleChunk self, SseSerializer serializer);

  @protected
  void sse_encode_subtitle_candidate(
    SubtitleCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtitle_preview_page(
    SubtitlePreviewPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_sample_plan(
    VideoSamplePlan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xunlei_candidate(
    XunleiCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
