// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'api/workflow.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ByteRange dco_decode_byte_range(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ByteRange> dco_decode_list_byte_range(dynamic raw);

  @protected
  List<MatchReason> dco_decode_list_match_reason(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SampleChunk> dco_decode_list_sample_chunk(dynamic raw);

  @protected
  List<WorkflowSubtitleCandidate> dco_decode_list_workflow_subtitle_candidate(
    dynamic raw,
  );

  @protected
  MatchReason dco_decode_match_reason(dynamic raw);

  @protected
  MatchReasonKind dco_decode_match_reason_kind(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SampleChunk dco_decode_sample_chunk(dynamic raw);

  @protected
  SubtitleArtifact dco_decode_subtitle_artifact(dynamic raw);

  @protected
  SubtitleFailure dco_decode_subtitle_failure(dynamic raw);

  @protected
  SubtitleFailureKind dco_decode_subtitle_failure_kind(dynamic raw);

  @protected
  SubtitleFormat dco_decode_subtitle_format(dynamic raw);

  @protected
  SubtitleOperation dco_decode_subtitle_operation(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoSamplePlan dco_decode_video_sample_plan(dynamic raw);

  @protected
  WorkflowSubtitleCandidate dco_decode_workflow_subtitle_candidate(dynamic raw);

  @protected
  WorkflowSubtitlePreviewPage dco_decode_workflow_subtitle_preview_page(
    dynamic raw,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ByteRange sse_decode_byte_range(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ByteRange> sse_decode_list_byte_range(SseDeserializer deserializer);

  @protected
  List<MatchReason> sse_decode_list_match_reason(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SampleChunk> sse_decode_list_sample_chunk(SseDeserializer deserializer);

  @protected
  List<WorkflowSubtitleCandidate> sse_decode_list_workflow_subtitle_candidate(
    SseDeserializer deserializer,
  );

  @protected
  MatchReason sse_decode_match_reason(SseDeserializer deserializer);

  @protected
  MatchReasonKind sse_decode_match_reason_kind(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SampleChunk sse_decode_sample_chunk(SseDeserializer deserializer);

  @protected
  SubtitleArtifact sse_decode_subtitle_artifact(SseDeserializer deserializer);

  @protected
  SubtitleFailure sse_decode_subtitle_failure(SseDeserializer deserializer);

  @protected
  SubtitleFailureKind sse_decode_subtitle_failure_kind(
    SseDeserializer deserializer,
  );

  @protected
  SubtitleFormat sse_decode_subtitle_format(SseDeserializer deserializer);

  @protected
  SubtitleOperation sse_decode_subtitle_operation(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoSamplePlan sse_decode_video_sample_plan(SseDeserializer deserializer);

  @protected
  WorkflowSubtitleCandidate sse_decode_workflow_subtitle_candidate(
    SseDeserializer deserializer,
  );

  @protected
  WorkflowSubtitlePreviewPage sse_decode_workflow_subtitle_preview_page(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_byte_range(ByteRange self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_byte_range(
    List<ByteRange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_match_reason(
    List<MatchReason> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sample_chunk(
    List<SampleChunk> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workflow_subtitle_candidate(
    List<WorkflowSubtitleCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_match_reason(MatchReason self, SseSerializer serializer);

  @protected
  void sse_encode_match_reason_kind(
    MatchReasonKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_sample_chunk(SampleChunk self, SseSerializer serializer);

  @protected
  void sse_encode_subtitle_artifact(
    SubtitleArtifact self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtitle_failure(
    SubtitleFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtitle_failure_kind(
    SubtitleFailureKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtitle_format(
    SubtitleFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtitle_operation(
    SubtitleOperation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_sample_plan(
    VideoSamplePlan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workflow_subtitle_candidate(
    WorkflowSubtitleCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workflow_subtitle_preview_page(
    WorkflowSubtitlePreviewPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
