// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'api/xunlei.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -321703386;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ss_subtitle_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleComputeCid({
    required BigInt fileSize,
    required List<SampleChunk> chunks,
  });

  String crateApiSimpleDeriveSearchName({required String filename});

  Future<Uint8List> crateApiXunleiDownloadXunlei({required String candidateId});

  Future<void> crateApiSimpleInitApp();

  VideoSamplePlan crateApiSimplePlanVideoSample({required BigInt fileSize});

  List<RankedSubtitleCandidate> crateApiSimpleRankSubtitleCandidates({
    required List<SubtitleCandidate> candidates,
    required CandidateRankingContext context,
  });

  Future<List<XunleiCandidate>> crateApiXunleiSearchXunlei({
    required String query,
  });

  SubtitlePreviewPage crateApiSimpleSubtitlePreviewPage({
    required List<int> bytes,
    required int page,
    required String format,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleComputeCid({
    required BigInt fileSize,
    required List<SampleChunk> chunks,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(fileSize, serializer);
          sse_encode_list_sample_chunk(chunks, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleComputeCidConstMeta,
        argValues: [fileSize, chunks],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleComputeCidConstMeta => const TaskConstMeta(
    debugName: "compute_cid",
    argNames: ["fileSize", "chunks"],
  );

  @override
  String crateApiSimpleDeriveSearchName({required String filename}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filename, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleDeriveSearchNameConstMeta,
        argValues: [filename],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeriveSearchNameConstMeta =>
      const TaskConstMeta(
        debugName: "derive_search_name",
        argNames: ["filename"],
      );

  @override
  Future<Uint8List> crateApiXunleiDownloadXunlei({
    required String candidateId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(candidateId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiXunleiDownloadXunleiConstMeta,
        argValues: [candidateId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXunleiDownloadXunleiConstMeta =>
      const TaskConstMeta(
        debugName: "download_xunlei",
        argNames: ["candidateId"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  VideoSamplePlan crateApiSimplePlanVideoSample({required BigInt fileSize}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(fileSize, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_sample_plan,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePlanVideoSampleConstMeta,
        argValues: [fileSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePlanVideoSampleConstMeta =>
      const TaskConstMeta(
        debugName: "plan_video_sample",
        argNames: ["fileSize"],
      );

  @override
  List<RankedSubtitleCandidate> crateApiSimpleRankSubtitleCandidates({
    required List<SubtitleCandidate> candidates,
    required CandidateRankingContext context,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_subtitle_candidate(candidates, serializer);
          sse_encode_box_autoadd_candidate_ranking_context(context, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ranked_subtitle_candidate,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleRankSubtitleCandidatesConstMeta,
        argValues: [candidates, context],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRankSubtitleCandidatesConstMeta =>
      const TaskConstMeta(
        debugName: "rank_subtitle_candidates",
        argNames: ["candidates", "context"],
      );

  @override
  Future<List<XunleiCandidate>> crateApiXunleiSearchXunlei({
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_xunlei_candidate,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiXunleiSearchXunleiConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiXunleiSearchXunleiConstMeta =>
      const TaskConstMeta(debugName: "search_xunlei", argNames: ["query"]);

  @override
  SubtitlePreviewPage crateApiSimpleSubtitlePreviewPage({
    required List<int> bytes,
    required int page,
    required String format,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_u_32(page, serializer);
          sse_encode_String(format, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_subtitle_preview_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSubtitlePreviewPageConstMeta,
        argValues: [bytes, page, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSubtitlePreviewPageConstMeta =>
      const TaskConstMeta(
        debugName: "subtitle_preview_page",
        argNames: ["bytes", "page", "format"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CandidateRankingContext dco_decode_box_autoadd_candidate_ranking_context(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_candidate_ranking_context(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ByteRange dco_decode_byte_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ByteRange(
      offset: dco_decode_u_64(arr[0]),
      length: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  CandidateRankingContext dco_decode_candidate_ranking_context(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CandidateRankingContext(
      searchName: dco_decode_String(arr[0]),
      videoCid: dco_decode_opt_String(arr[1]),
      videoDurationMillis: dco_decode_opt_box_autoadd_u_64(arr[2]),
      preferredLanguages: dco_decode_list_String(arr[3]),
      preferredFormats: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ByteRange> dco_decode_list_byte_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_byte_range).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RankedSubtitleCandidate> dco_decode_list_ranked_subtitle_candidate(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_ranked_subtitle_candidate)
        .toList();
  }

  @protected
  List<SampleChunk> dco_decode_list_sample_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sample_chunk).toList();
  }

  @protected
  List<SubtitleCandidate> dco_decode_list_subtitle_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_subtitle_candidate).toList();
  }

  @protected
  List<XunleiCandidate> dco_decode_list_xunlei_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_xunlei_candidate).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  RankedSubtitleCandidate dco_decode_ranked_subtitle_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RankedSubtitleCandidate(
      candidate: dco_decode_subtitle_candidate(arr[0]),
      score: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  SampleChunk dco_decode_sample_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SampleChunk(
      offset: dco_decode_u_64(arr[0]),
      bytes: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  SubtitleCandidate dco_decode_subtitle_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SubtitleCandidate(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      cid: dco_decode_opt_String(arr[2]),
      durationMillis: dco_decode_opt_box_autoadd_u_64(arr[3]),
      language: dco_decode_opt_String(arr[4]),
      format: dco_decode_String(arr[5]),
      upstreamScore: dco_decode_i_64(arr[6]),
      fingerprintMatch: dco_decode_bool(arr[7]),
    );
  }

  @protected
  SubtitlePreviewPage dco_decode_subtitle_preview_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SubtitlePreviewPage(
      lines: dco_decode_list_String(arr[0]),
      page: dco_decode_u_32(arr[1]),
      pageSize: dco_decode_u_32(arr[2]),
      totalLines: dco_decode_u_32(arr[3]),
      totalPages: dco_decode_u_32(arr[4]),
      encoding: dco_decode_String(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoSamplePlan dco_decode_video_sample_plan(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return VideoSamplePlan(
      fileSize: dco_decode_u_64(arr[0]),
      ranges: dco_decode_list_byte_range(arr[1]),
    );
  }

  @protected
  XunleiCandidate dco_decode_xunlei_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return XunleiCandidate(
      candidateId: dco_decode_String(arr[0]),
      extension_: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      durationMs: dco_decode_opt_box_autoadd_u_64(arr[3]),
      languages: dco_decode_list_String(arr[4]),
      upstreamScore: dco_decode_opt_box_autoadd_f_64(arr[5]),
      fingerprintScore: dco_decode_opt_box_autoadd_f_64(arr[6]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CandidateRankingContext sse_decode_box_autoadd_candidate_ranking_context(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_candidate_ranking_context(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ByteRange sse_decode_byte_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_offset = sse_decode_u_64(deserializer);
    var var_length = sse_decode_u_64(deserializer);
    return ByteRange(offset: var_offset, length: var_length);
  }

  @protected
  CandidateRankingContext sse_decode_candidate_ranking_context(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_searchName = sse_decode_String(deserializer);
    var var_videoCid = sse_decode_opt_String(deserializer);
    var var_videoDurationMillis = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_preferredLanguages = sse_decode_list_String(deserializer);
    var var_preferredFormats = sse_decode_list_String(deserializer);
    return CandidateRankingContext(
      searchName: var_searchName,
      videoCid: var_videoCid,
      videoDurationMillis: var_videoDurationMillis,
      preferredLanguages: var_preferredLanguages,
      preferredFormats: var_preferredFormats,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ByteRange> sse_decode_list_byte_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ByteRange>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_byte_range(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RankedSubtitleCandidate> sse_decode_list_ranked_subtitle_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RankedSubtitleCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ranked_subtitle_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  List<SampleChunk> sse_decode_list_sample_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SampleChunk>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sample_chunk(deserializer));
    }
    return ans_;
  }

  @protected
  List<SubtitleCandidate> sse_decode_list_subtitle_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SubtitleCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_subtitle_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  List<XunleiCandidate> sse_decode_list_xunlei_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <XunleiCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_xunlei_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RankedSubtitleCandidate sse_decode_ranked_subtitle_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_candidate = sse_decode_subtitle_candidate(deserializer);
    var var_score = sse_decode_i_64(deserializer);
    return RankedSubtitleCandidate(candidate: var_candidate, score: var_score);
  }

  @protected
  SampleChunk sse_decode_sample_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_offset = sse_decode_u_64(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return SampleChunk(offset: var_offset, bytes: var_bytes);
  }

  @protected
  SubtitleCandidate sse_decode_subtitle_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_cid = sse_decode_opt_String(deserializer);
    var var_durationMillis = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_upstreamScore = sse_decode_i_64(deserializer);
    var var_fingerprintMatch = sse_decode_bool(deserializer);
    return SubtitleCandidate(
      id: var_id,
      name: var_name,
      cid: var_cid,
      durationMillis: var_durationMillis,
      language: var_language,
      format: var_format,
      upstreamScore: var_upstreamScore,
      fingerprintMatch: var_fingerprintMatch,
    );
  }

  @protected
  SubtitlePreviewPage sse_decode_subtitle_preview_page(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lines = sse_decode_list_String(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_pageSize = sse_decode_u_32(deserializer);
    var var_totalLines = sse_decode_u_32(deserializer);
    var var_totalPages = sse_decode_u_32(deserializer);
    var var_encoding = sse_decode_String(deserializer);
    return SubtitlePreviewPage(
      lines: var_lines,
      page: var_page,
      pageSize: var_pageSize,
      totalLines: var_totalLines,
      totalPages: var_totalPages,
      encoding: var_encoding,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoSamplePlan sse_decode_video_sample_plan(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileSize = sse_decode_u_64(deserializer);
    var var_ranges = sse_decode_list_byte_range(deserializer);
    return VideoSamplePlan(fileSize: var_fileSize, ranges: var_ranges);
  }

  @protected
  XunleiCandidate sse_decode_xunlei_candidate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_candidateId = sse_decode_String(deserializer);
    var var_extension_ = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_languages = sse_decode_list_String(deserializer);
    var var_upstreamScore = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_fingerprintScore = sse_decode_opt_box_autoadd_f_64(deserializer);
    return XunleiCandidate(
      candidateId: var_candidateId,
      extension_: var_extension_,
      name: var_name,
      durationMs: var_durationMs,
      languages: var_languages,
      upstreamScore: var_upstreamScore,
      fingerprintScore: var_fingerprintScore,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_candidate_ranking_context(
    CandidateRankingContext self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_candidate_ranking_context(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_byte_range(ByteRange self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.offset, serializer);
    sse_encode_u_64(self.length, serializer);
  }

  @protected
  void sse_encode_candidate_ranking_context(
    CandidateRankingContext self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.searchName, serializer);
    sse_encode_opt_String(self.videoCid, serializer);
    sse_encode_opt_box_autoadd_u_64(self.videoDurationMillis, serializer);
    sse_encode_list_String(self.preferredLanguages, serializer);
    sse_encode_list_String(self.preferredFormats, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_byte_range(
    List<ByteRange> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_byte_range(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_ranked_subtitle_candidate(
    List<RankedSubtitleCandidate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ranked_subtitle_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_list_sample_chunk(
    List<SampleChunk> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sample_chunk(item, serializer);
    }
  }

  @protected
  void sse_encode_list_subtitle_candidate(
    List<SubtitleCandidate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_subtitle_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_list_xunlei_candidate(
    List<XunleiCandidate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_xunlei_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_ranked_subtitle_candidate(
    RankedSubtitleCandidate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_subtitle_candidate(self.candidate, serializer);
    sse_encode_i_64(self.score, serializer);
  }

  @protected
  void sse_encode_sample_chunk(SampleChunk self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.offset, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_subtitle_candidate(
    SubtitleCandidate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.cid, serializer);
    sse_encode_opt_box_autoadd_u_64(self.durationMillis, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_i_64(self.upstreamScore, serializer);
    sse_encode_bool(self.fingerprintMatch, serializer);
  }

  @protected
  void sse_encode_subtitle_preview_page(
    SubtitlePreviewPage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.lines, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.pageSize, serializer);
    sse_encode_u_32(self.totalLines, serializer);
    sse_encode_u_32(self.totalPages, serializer);
    sse_encode_String(self.encoding, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_sample_plan(
    VideoSamplePlan self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.fileSize, serializer);
    sse_encode_list_byte_range(self.ranges, serializer);
  }

  @protected
  void sse_encode_xunlei_candidate(
    XunleiCandidate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.candidateId, serializer);
    sse_encode_String(self.extension_, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_box_autoadd_u_64(self.durationMs, serializer);
    sse_encode_list_String(self.languages, serializer);
    sse_encode_opt_box_autoadd_f_64(self.upstreamScore, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fingerprintScore, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
