// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_subtitle`, `decode_utf16`, `normalized_title`, `validate_subtitle_text`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

String deriveSearchName({required String filename}) =>
    RustLib.instance.api.crateApiSimpleDeriveSearchName(filename: filename);

VideoSamplePlan planVideoSample({required BigInt fileSize}) =>
    RustLib.instance.api.crateApiSimplePlanVideoSample(fileSize: fileSize);

String computeCid({
  required BigInt fileSize,
  required List<SampleChunk> chunks,
}) => RustLib.instance.api.crateApiSimpleComputeCid(
  fileSize: fileSize,
  chunks: chunks,
);

class ByteRange {
  final BigInt offset;
  final BigInt length;

  const ByteRange({required this.offset, required this.length});

  @override
  int get hashCode => offset.hashCode ^ length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ByteRange &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          length == other.length;
}

class SampleChunk {
  final BigInt offset;
  final Uint8List bytes;

  const SampleChunk({required this.offset, required this.bytes});

  @override
  int get hashCode => offset.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SampleChunk &&
          runtimeType == other.runtimeType &&
          offset == other.offset &&
          bytes == other.bytes;
}

class VideoSamplePlan {
  final BigInt fileSize;
  final List<ByteRange> ranges;

  const VideoSamplePlan({required this.fileSize, required this.ranges});

  @override
  int get hashCode => fileSize.hashCode ^ ranges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoSamplePlan &&
          runtimeType == other.runtimeType &&
          fileSize == other.fileSize &&
          ranges == other.ranges;
}
