// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `acquire_subtitle`, `as_str`, `boxed_workflow_future`, `default_workflow`, `internal_failure`, `new`, `normalize_languages`, `parse`, `preview_subtitle`, `search_subtitles`, `stable_candidate_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SubtitleWorkflow`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `hash`

Future<List<WorkflowSubtitleCandidate>> searchSubtitles({
  required String suggestedSearchName,
}) => RustLib.instance.api.crateApiWorkflowSearchSubtitles(
  suggestedSearchName: suggestedSearchName,
);

Future<WorkflowSubtitlePreviewPage> previewSubtitle({
  required String candidateId,
  required int page,
}) => RustLib.instance.api.crateApiWorkflowPreviewSubtitle(
  candidateId: candidateId,
  page: page,
);

Future<SubtitleArtifact> acquireSubtitle({required String candidateId}) =>
    RustLib.instance.api.crateApiWorkflowAcquireSubtitle(
      candidateId: candidateId,
    );

class MatchReason {
  final MatchReasonKind kind;
  final String? value;

  const MatchReason({required this.kind, this.value});

  @override
  int get hashCode => kind.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchReason &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          value == other.value;
}

enum MatchReasonKind {
  exactTitle,
  titleContains,
  languageMatch,
  providerScore,
  fingerprintMatch,
  supportedFormat,
}

class SubtitleArtifact {
  final String candidateId;
  final Uint8List bytes;
  final SubtitleFormat format;

  const SubtitleArtifact({
    required this.candidateId,
    required this.bytes,
    required this.format,
  });

  @override
  int get hashCode => candidateId.hashCode ^ bytes.hashCode ^ format.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtitleArtifact &&
          runtimeType == other.runtimeType &&
          candidateId == other.candidateId &&
          bytes == other.bytes &&
          format == other.format;
}

class SubtitleFailure implements FrbException {
  final SubtitleOperation operation;
  final SubtitleFailureKind kind;
  final String? detail;

  const SubtitleFailure({
    required this.operation,
    required this.kind,
    this.detail,
  });

  @override
  int get hashCode => operation.hashCode ^ kind.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtitleFailure &&
          runtimeType == other.runtimeType &&
          operation == other.operation &&
          kind == other.kind &&
          detail == other.detail;
}

enum SubtitleFailureKind {
  invalidSuggestedSearchName,
  candidateExpired,
  providerUnavailable,
  artifactTooLarge,
  artifactInvalid,
  previewPageOutOfRange,
  internal,
}

enum SubtitleFormat { srt, ass, ssa, vtt }

enum SubtitleOperation { search, preview, acquisition }

class WorkflowSubtitleCandidate {
  final String id;
  final String name;
  final List<String> languages;
  final SubtitleFormat format;
  final PlatformInt64 matchScore;
  final List<MatchReason> matchReasons;

  const WorkflowSubtitleCandidate({
    required this.id,
    required this.name,
    required this.languages,
    required this.format,
    required this.matchScore,
    required this.matchReasons,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      languages.hashCode ^
      format.hashCode ^
      matchScore.hashCode ^
      matchReasons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkflowSubtitleCandidate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          languages == other.languages &&
          format == other.format &&
          matchScore == other.matchScore &&
          matchReasons == other.matchReasons;
}

class WorkflowSubtitlePreviewPage {
  final String candidateId;
  final List<String> lines;
  final int page;
  final int totalPages;

  const WorkflowSubtitlePreviewPage({
    required this.candidateId,
    required this.lines,
    required this.page,
    required this.totalPages,
  });

  @override
  int get hashCode =>
      candidateId.hashCode ^
      lines.hashCode ^
      page.hashCode ^
      totalPages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkflowSubtitlePreviewPage &&
          runtimeType == other.runtimeType &&
          candidateId == other.candidateId &&
          lines == other.lines &&
          page == other.page &&
          totalPages == other.totalPages;
}
