// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `allowed_host`, `as_str`, `build_client`, `candidate_registry`, `insert`, `parse_search_payload`, `parse`, `read_limited`, `stable_candidate_id`, `subtitle_sample_text`, `validate_download_url`, `validate_response_url`, `validate_subtitle_content`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CandidateRegistry`, `RegisteredCandidate`, `SubtitleExtension`, `XunleiCandidateWire`, `XunleiSearchResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Search Xunlei by an editable Suggested Search Name.
///
/// Only `query` is sent to Xunlei. Candidate URLs remain in a bounded native
/// registry and are represented across FRB by opaque SHA-1 identifiers.
Future<List<XunleiCandidate>> searchXunlei({required String query}) =>
    RustLib.instance.api.crateApiXunleiSearchXunlei(query: query);

/// Download a previously searched Xunlei Subtitle Candidate.
///
/// The opaque ID must still exist in the process-local bounded registry. The
/// implementation streams the response and aborts before it exceeds 20 MiB.
Future<Uint8List> downloadXunlei({required String candidateId}) =>
    RustLib.instance.api.crateApiXunleiDownloadXunlei(candidateId: candidateId);

/// A Xunlei subtitle candidate safe to send across flutter_rust_bridge.
///
/// The provider download URL is deliberately absent. Callers can download a
/// candidate only through its opaque `candidate_id`.
class XunleiCandidate {
  final String candidateId;
  final String extension_;
  final String name;
  final BigInt? durationMs;
  final List<String> languages;
  final double? upstreamScore;
  final double? fingerprintScore;

  const XunleiCandidate({
    required this.candidateId,
    required this.extension_,
    required this.name,
    this.durationMs,
    required this.languages,
    this.upstreamScore,
    this.fingerprintScore,
  });

  @override
  int get hashCode =>
      candidateId.hashCode ^
      extension_.hashCode ^
      name.hashCode ^
      durationMs.hashCode ^
      languages.hashCode ^
      upstreamScore.hashCode ^
      fingerprintScore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XunleiCandidate &&
          runtimeType == other.runtimeType &&
          candidateId == other.candidateId &&
          extension_ == other.extension_ &&
          name == other.name &&
          durationMs == other.durationMs &&
          languages == other.languages &&
          upstreamScore == other.upstreamScore &&
          fingerprintScore == other.fingerprintScore;
}
